### ISSUE TITLE
err on `npm run open`

### ISSUE THREAD

**Issue by jennifer-shehane** [bahmutov/test-vue-vuex#1]
```bash
$ npm run open

> test-vue-vuex@1.0.0 open /Users/jennifer/Dev/Projects/test-vue-vuex
> start-server-and-test start http://localhost:3000 test

/Users/jennifer/Dev/Projects/test-vue-vuex/node_modules/start-server-and-test/bin/start.js:8
let start = 'start'
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by jennifer-shehane** [comment]
Is this repo missing deps? Cause I'm getting errors all over the place 😢 

```
$ npm run start

> test-vue-vuex@1.0.0 start /Users/jennifer/Dev/Projects/test-vue-vuex
> json-server --static . data.json --middlewares node_modules/json-server-reset

/Users/jennifer/Dev/Projects/test-vue-vuex/node_modules/chalk/index.js:72
ansiStyles.color.closeRe = new RegExp(escapeStringRegexp(ansiStyles.color.close), 'g');
                                                                         ^

TypeError: Cannot read property 'close' of undefined
    at Object.<anonymous> (/Users/jennifer/Dev/Projects/test-vue-vuex/node_modules/chalk/index.js:72:74)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jennifer/Dev/Projects/test-vue-vuex/node_modules/json-server/lib/cli/run.js:7:13)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

**Comment by bahmutov** [comment]
errors like `let start = 'start'` are usually due to older version of Node. Are you sure you are using node 8? I added engines, but would ignore this repo, it is pretty old and has been taken over by https://github.com/bahmutov/cypress-vue-unit-test

**Comment by jennifer-shehane** [comment]
No, I was likely not on Node 8. I always use `.node-version` file to know. :?

**Comment by bahmutov** [comment]
I don't put `.node-version` in my repos :)

**Comment by jennifer-shehane** [comment]
How is someone supposed to know what node version to be on?

**Comment by bahmutov** [comment]
Hehe I added engines property to the package json here. This repo was really a throw away for testing so it did not need it yet.

**Comment by jennifer-shehane** [comment]
Yeah, was just curious what is most common way to communicate this in projects. Thanks.

**Comment by bahmutov** [comment]
Via engines where you can set both node and npm versions
